/** @deprecated 使用 oxsp-catalog.ts */
export {
  loadPinExtensionCatalog,
  savePinExtensionCatalog,
  addWebCardToCatalog,
  removeWebCardFromCatalog,
  findWebCard,
  webCardLabel,
  normalizeExtensionUrl,
  newWebCardId,
  webWidgetId,
  extWidgetId,
  PIN_EXTENSION_DEMO_URL,
  loadOxspCatalog,
  saveOxspCatalog,
  addOxspSlot,
  findOxspSlot,
  oxspSlotLabel,
  removeOxspSlot,
  updateOxspSlot,
  emptyOxspCatalog,
  type OxspSlotCatalog,
  type PinExtensionCatalog,
} from "./oxsp-catalog";
